lsi: false
pygments: true
url: http://s3-eu-west-1.amazonaws.com/arts-staging
urlgithub : http://artslondon.github.com/beta/
exclude: [styles, config.rb, config_live.rb, config_local.rb, config_staging.rb, gruntfile.js, package.json, Gemfile, Gemfile.lock, Guardfile, README.md]
baseurl: /docs/
