lsi: false
pygments: true
url: http://d27lwoqz7s24cy.cloudfront.net
urlgithub : http://artslondon.github.com/beta/
exclude: [styles, config.rb, config_live.rb, config_local.rb, config_staging.rb, gruntfile.js, package.json, Gemfile, Gemfile.lock, Guardfile, README.md]
baseurl: /docs/
