safe: true
lsi: false
pygments: true
url: /beta
exclude: [Gemfile, node_modules, temp, grunt-aws.json, styles, config.rb, config_live.rb, config_local.rb, config_staging.rb, gruntfile.js, package.json, Gemfile.lock, Guardfile, README.md]
permalink: date

# Run Jekyll using local config: jekyll build -w --config _config_local.yml

